"""Decision schema for crawled pages (GLiNER2.5-Decide + heuristic fallback)."""

from __future__ import annotations

from typing import Any

SCHEMA_VERSION = "v5"

_LEVELS = {
    "none": 0.0,
    "low": 0.25,
    "medium": 0.5,
    "high": 0.75,
    "extreme": 1.0,
}

_TRUE = {"true", "yes", "1", "human", "ai"}

PAGE_SCHEMA: dict[str, Any] = {
    "is_human_generated": {
        "type": "boolean",
        "description": (
            "The web page text is written by a human. It contains natural stylistic "
            "variations, unique phrasing, personal anecdotes, or minor colloquial irregularities."
        ),
    },
    "is_ai_generated": {
        "type": "boolean",
        "description": (
            "The web page text is generated by an AI. It exhibits highly predictable "
            "structures, repetitive transitional phrases, uniform sentence lengths, "
            "or a sterile, overly polished tone."
        ),
    },
    "thought_quality": {
        "type": "labels",
        "labels": ["none", "low", "medium", "high", "extreme"],
        "prompt": (
            "Score independent writing. Personal technical essays, illustrated explainers, "
            "and encyclopedia articles can be high. UI, navigation, comments, and platform "
            "marketing are low."
        ),
    },
    "commercial_bias": {
        "type": "labels",
        "labels": ["none", "low", "medium", "high", "extreme"],
        "prompt": "How strongly is this page selling a product, service, or course?",
    },
    "ad_use": {
        "type": "labels",
        "labels": ["none", "low", "medium", "high", "extreme"],
        "prompt": "How much of the page is ads, sponsors, or ad trackers?",
    },
    "commercial_promotion": {
        "type": "labels",
        "labels": ["none", "low", "medium", "high", "extreme"],
        "prompt": "How much is this page itself a promotion or affiliate pitch?",
    },
    "citation_use": {
        "type": "labels",
        "labels": ["none", "low", "medium", "high", "extreme"],
        "prompt": "How clearly does this page cite sources with real, useful references?",
    },
}


def level_to_unit(value: Any, default: float = 0.0) -> float:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return max(0.0, min(1.0, float(value)))
    text = str(value or "").strip().lower()
    if text in _LEVELS:
        return _LEVELS[text]
    try:
        return max(0.0, min(1.0, float(text)))
    except ValueError:
        return default


def as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    return str(value or "").strip().lower() in _TRUE


def authorship_flags(decisions: dict[str, Any]) -> tuple[bool, bool]:
    """Return (is_human, is_ai). Both-true is clamped to neither (unknown)."""
    has_bools = "is_human_generated" in decisions or "is_ai_generated" in decisions
    if has_bools:
        is_human = as_bool(decisions.get("is_human_generated"))
        is_ai = as_bool(decisions.get("is_ai_generated"))
    else:
        label = str(decisions.get("authorship_likeness") or "unknown").strip().lower()
        is_human = label == "human_crafted"
        is_ai = label == "synthetic_filler"
    if is_human and is_ai:
        return False, False
    return is_human, is_ai


def authorship_label(is_human: bool, is_ai: bool) -> str:
    if is_human and not is_ai:
        return "human_crafted"
    if is_ai and not is_human:
        return "synthetic_filler"
    return "unknown"


def numeric_decisions(decisions: dict[str, Any]) -> dict[str, Any]:
    """Normalize heads: exclusive authorship booleans, level heads in 0–1."""
    is_human, is_ai = authorship_flags(decisions)
    out = dict(decisions)
    out["is_human_generated"] = is_human
    out["is_ai_generated"] = is_ai
    out["authorship_likeness"] = authorship_label(is_human, is_ai)
    for key in ("thought_quality", "commercial_bias", "ad_use", "commercial_promotion", "citation_use"):
        out[key] = level_to_unit(decisions.get(key), 0.0)
    return out


def badges_from_decisions(decisions: dict[str, Any]) -> list[str]:
    badges: list[str] = []
    authorship = str(decisions.get("authorship_likeness", "")).lower()
    if as_bool(decisions.get("is_ai_generated")) or authorship == "synthetic_filler":
        badges.append("ai_slop")
    if as_bool(decisions.get("is_human_generated")) or authorship == "human_crafted":
        badges.append("human_craft")
    for field, value, badge in (
        ("bot_spam", "yes", "bot_spam"),
        ("propaganda_signal", "clear", "propaganda"),
        ("malice", "scam_or_harm", "malicious"),
    ):
        if str(decisions.get(field, "")).lower() == value:
            badges.append(badge)
    niche = str(decisions.get("niche_value", "")).lower()
    raw_quality = str(decisions.get("thought_quality", "")).strip()
    try:
        quality = float(raw_quality)
    except ValueError:
        quality = level_to_unit(raw_quality, 0.0) * 5.0
    if raw_quality not in {"1", "2", "3", "4", "5"} and quality <= 1.0:
        quality *= 5.0
    human_enough = as_bool(decisions.get("is_human_generated")) or authorship == "human_crafted" or (
        authorship == "mixed" and quality >= 4
    )
    if human_enough and quality >= 4:
        if niche == "rare_gem":
            badges.append("rare_gem")
        elif niche == "specialist_useful":
            badges.append("niche")
    if quality >= 4:
        badges.append("high_thought")
    if str(decisions.get("bot_spam", "")).lower() == "yes":
        badges = [badge for badge in badges if badge not in {"rare_gem", "niche", "high_thought"}]
    if str(decisions.get("malice", "")).lower() == "scam_or_harm":
        badges = [badge for badge in badges if badge not in {"rare_gem", "niche", "high_thought", "human_craft"}]
    return badges
